# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ConceptCode(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, concept=None, code=None):  # noqa: E501
        """ConceptCode - a model defined in OpenAPI

        :param concept: The concept of this ConceptCode.  # noqa: E501
        :type concept: str
        :param code: The code of this ConceptCode.  # noqa: E501
        :type code: str
        """
        self.openapi_types = {
            'concept': str,
            'code': str
        }

        self.attribute_map = {
            'concept': 'concept',
            'code': 'code'
        }

        self._concept = concept
        self._code = code

    @classmethod
    def from_dict(cls, dikt) -> 'ConceptCode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConceptCode of this ConceptCode.  # noqa: E501
        :rtype: ConceptCode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def concept(self):
        """Gets the concept of this ConceptCode.


        :return: The concept of this ConceptCode.
        :rtype: str
        """
        return self._concept

    @concept.setter
    def concept(self, concept):
        """Sets the concept of this ConceptCode.


        :param concept: The concept of this ConceptCode.
        :type concept: str
        """

        self._concept = concept

    @property
    def code(self):
        """Gets the code of this ConceptCode.


        :return: The code of this ConceptCode.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ConceptCode.


        :param code: The code of this ConceptCode.
        :type code: str
        """

        self._code = code
