# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ConceptTerm(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, concept=None, term=None):  # noqa: E501
        """ConceptTerm - a model defined in OpenAPI

        :param concept: The concept of this ConceptTerm.  # noqa: E501
        :type concept: str
        :param term: The term of this ConceptTerm.  # noqa: E501
        :type term: str
        """
        self.openapi_types = {
            'concept': str,
            'term': str
        }

        self.attribute_map = {
            'concept': 'concept',
            'term': 'term'
        }

        self._concept = concept
        self._term = term

    @classmethod
    def from_dict(cls, dikt) -> 'ConceptTerm':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConceptTerm of this ConceptTerm.  # noqa: E501
        :rtype: ConceptTerm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def concept(self):
        """Gets the concept of this ConceptTerm.


        :return: The concept of this ConceptTerm.
        :rtype: str
        """
        return self._concept

    @concept.setter
    def concept(self, concept):
        """Sets the concept of this ConceptTerm.


        :param concept: The concept of this ConceptTerm.
        :type concept: str
        """

        self._concept = concept

    @property
    def term(self):
        """Gets the term of this ConceptTerm.


        :return: The term of this ConceptTerm.
        :rtype: str
        """
        return self._term

    @term.setter
    def term(self, term):
        """Sets the term of this ConceptTerm.


        :param term: The term of this ConceptTerm.
        :type term: str
        """

        self._term = term
