# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ConceptPrefterm(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, concept=None, prefterm=None):  # noqa: E501
        """ConceptPrefterm - a model defined in OpenAPI

        :param concept: The concept of this ConceptPrefterm.  # noqa: E501
        :type concept: str
        :param prefterm: The prefterm of this ConceptPrefterm.  # noqa: E501
        :type prefterm: str
        """
        self.openapi_types = {
            'concept': str,
            'prefterm': str
        }

        self.attribute_map = {
            'concept': 'concept',
            'prefterm': 'prefterm'
        }

        self._concept = concept
        self._prefterm = prefterm

    @classmethod
    def from_dict(cls, dikt) -> 'ConceptPrefterm':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConceptPrefterm of this ConceptPrefterm.  # noqa: E501
        :rtype: ConceptPrefterm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def concept(self):
        """Gets the concept of this ConceptPrefterm.


        :return: The concept of this ConceptPrefterm.
        :rtype: str
        """
        return self._concept

    @concept.setter
    def concept(self, concept):
        """Sets the concept of this ConceptPrefterm.


        :param concept: The concept of this ConceptPrefterm.
        :type concept: str
        """

        self._concept = concept

    @property
    def prefterm(self):
        """Gets the prefterm of this ConceptPrefterm.


        :return: The prefterm of this ConceptPrefterm.
        :rtype: str
        """
        return self._prefterm

    @prefterm.setter
    def prefterm(self, prefterm):
        """Sets the prefterm of this ConceptPrefterm.


        :param prefterm: The prefterm of this ConceptPrefterm.
        :type prefterm: str
        """

        self._prefterm = prefterm
