# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class SabRelationshipConceptPrefterm(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sab=None, relationship=None, concept=None, perfterm=None):  # noqa: E501
        """SabRelationshipConceptPrefterm - a model defined in OpenAPI

        :param sab: The sab of this SabRelationshipConceptPrefterm.  # noqa: E501
        :type sab: str
        :param relationship: The relationship of this SabRelationshipConceptPrefterm.  # noqa: E501
        :type relationship: str
        :param concept: The concept of this SabRelationshipConceptPrefterm.  # noqa: E501
        :type concept: str
        :param perfterm: The perfterm of this SabRelationshipConceptPrefterm.  # noqa: E501
        :type perfterm: str
        """
        self.openapi_types = {
            'sab': str,
            'relationship': str,
            'concept': str,
            'perfterm': str
        }

        self.attribute_map = {
            'sab': 'sab',
            'relationship': 'relationship',
            'concept': 'concept',
            'perfterm': 'perfterm'
        }

        self._sab = sab
        self._relationship = relationship
        self._concept = concept
        self._perfterm = perfterm

    @classmethod
    def from_dict(cls, dikt) -> 'SabRelationshipConceptPrefterm':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SabRelationshipConceptPrefterm of this SabRelationshipConceptPrefterm.  # noqa: E501
        :rtype: SabRelationshipConceptPrefterm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sab(self):
        """Gets the sab of this SabRelationshipConceptPrefterm.


        :return: The sab of this SabRelationshipConceptPrefterm.
        :rtype: str
        """
        return self._sab

    @sab.setter
    def sab(self, sab):
        """Sets the sab of this SabRelationshipConceptPrefterm.


        :param sab: The sab of this SabRelationshipConceptPrefterm.
        :type sab: str
        """

        self._sab = sab

    @property
    def relationship(self):
        """Gets the relationship of this SabRelationshipConceptPrefterm.


        :return: The relationship of this SabRelationshipConceptPrefterm.
        :rtype: str
        """
        return self._relationship

    @relationship.setter
    def relationship(self, relationship):
        """Sets the relationship of this SabRelationshipConceptPrefterm.


        :param relationship: The relationship of this SabRelationshipConceptPrefterm.
        :type relationship: str
        """

        self._relationship = relationship

    @property
    def concept(self):
        """Gets the concept of this SabRelationshipConceptPrefterm.


        :return: The concept of this SabRelationshipConceptPrefterm.
        :rtype: str
        """
        return self._concept

    @concept.setter
    def concept(self, concept):
        """Sets the concept of this SabRelationshipConceptPrefterm.


        :param concept: The concept of this SabRelationshipConceptPrefterm.
        :type concept: str
        """

        self._concept = concept

    @property
    def perfterm(self):
        """Gets the perfterm of this SabRelationshipConceptPrefterm.


        :return: The perfterm of this SabRelationshipConceptPrefterm.
        :rtype: str
        """
        return self._perfterm

    @perfterm.setter
    def perfterm(self, perfterm):
        """Sets the perfterm of this SabRelationshipConceptPrefterm.


        :param perfterm: The perfterm of this SabRelationshipConceptPrefterm.
        :type perfterm: str
        """

        self._perfterm = perfterm
