# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class SemanticStn(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, semantic=None, stn=None):  # noqa: E501
        """SemanticStn - a model defined in OpenAPI

        :param semantic: The semantic of this SemanticStn.  # noqa: E501
        :type semantic: str
        :param stn: The stn of this SemanticStn.  # noqa: E501
        :type stn: str
        """
        self.openapi_types = {
            'semantic': str,
            'stn': str
        }

        self.attribute_map = {
            'semantic': 'semantic',
            'stn': 'STN'
        }

        self._semantic = semantic
        self._stn = stn

    @classmethod
    def from_dict(cls, dikt) -> 'SemanticStn':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SemanticStn of this SemanticStn.  # noqa: E501
        :rtype: SemanticStn
        """
        return util.deserialize_model(dikt, cls)

    @property
    def semantic(self):
        """Gets the semantic of this SemanticStn.


        :return: The semantic of this SemanticStn.
        :rtype: str
        """
        return self._semantic

    @semantic.setter
    def semantic(self, semantic):
        """Sets the semantic of this SemanticStn.


        :param semantic: The semantic of this SemanticStn.
        :type semantic: str
        """

        self._semantic = semantic

    @property
    def stn(self):
        """Gets the stn of this SemanticStn.


        :return: The stn of this SemanticStn.
        :rtype: str
        """
        return self._stn

    @stn.setter
    def stn(self, stn):
        """Sets the stn of this SemanticStn.


        :param stn: The stn of this SemanticStn.
        :type stn: str
        """

        self._stn = stn
